### ISSUE TITLE
LoadM reads incorrectly the rows (weak labels) and columns (true labels)

### ISSUE THREAD

**Issue by perellonieto** [Orieus/WeakLabelModel#11]
I think the check that is done when loading a mixing matrix M is wrong as it confuses the rows by columns. If somebody can confirm this I will fix the issue.

https://github.com/Orieus/WeakLabelModel/blob/f8be15a628f45e9c0980b854318eb26bc87b2574/weaklabels/WLweakener.py#L603

**Comment by DaniBacaicoa** [comment]
Yes, it should be 
nw, nc = M.shape

**Comment by perellonieto** [comment]
Oks thanks. Commit 20a1af41767e1aa349d78fdaaf08eb2974ef6a61 closes this issue.
